from database import SessionLocal, init_db, Load

LOADS = [
    {
        "load_id": "LD-001",
        "origin": "Chicago, IL",
        "destination": "Atlanta, GA",
        "pickup_datetime": "2026-04-17T08:00:00",
        "delivery_datetime": "2026-04-18T18:00:00",
        "equipment_type": "Dry Van",
        "loadboard_rate": 2450.00,
        "notes": "No-touch freight. Dock doors available.",
        "weight": 42000.0,
        "commodity_type": "Electronics",
        "num_of_pieces": 20,
        "miles": 716.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-002",
        "origin": "Dallas, TX",
        "destination": "Los Angeles, CA",
        "pickup_datetime": "2026-04-17T10:00:00",
        "delivery_datetime": "2026-04-19T14:00:00",
        "equipment_type": "Reefer",
        "loadboard_rate": 3800.00,
        "notes": "Temp set to 34°F. Continuous temp monitoring required.",
        "weight": 38000.0,
        "commodity_type": "Frozen Food",
        "num_of_pieces": 24,
        "miles": 1435.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-003",
        "origin": "Detroit, MI",
        "destination": "Nashville, TN",
        "pickup_datetime": "2026-04-17T07:00:00",
        "delivery_datetime": "2026-04-18T12:00:00",
        "equipment_type": "Flatbed",
        "loadboard_rate": 1950.00,
        "notes": "Tarping required. Straps provided by shipper.",
        "weight": 44000.0,
        "commodity_type": "Auto Parts",
        "num_of_pieces": 6,
        "miles": 531.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-004",
        "origin": "Phoenix, AZ",
        "destination": "Denver, CO",
        "pickup_datetime": "2026-04-18T09:00:00",
        "delivery_datetime": "2026-04-19T17:00:00",
        "equipment_type": "Dry Van",
        "loadboard_rate": 1750.00,
        "notes": "Team driver not required. 2 stop delivery.",
        "weight": 36000.0,
        "commodity_type": "Building Materials",
        "num_of_pieces": 33,
        "miles": 602.0,
        "dimensions": "53x102",
        "status": "available",
    },
    {
        "load_id": "LD-005",
        "origin": "Miami, FL",
        "destination": "New York, NY",
        "pickup_datetime": "2026-04-17T06:00:00",
        "delivery_datetime": "2026-04-19T08:00:00",
        "equipment_type": "Reefer",
        "loadboard_rate": 4200.00,
        "notes": "Temp set to 38°F. FSMA compliant carrier required.",
        "weight": 40000.0,
        "commodity_type": "Fresh Produce",
        "num_of_pieces": 28,
        "miles": 1280.0,
        "dimensions": "53x102",
        "status": "available",
    },
    {
        "load_id": "LD-006",
        "origin": "Seattle, WA",
        "destination": "San Francisco, CA",
        "pickup_datetime": "2026-04-18T08:00:00",
        "delivery_datetime": "2026-04-19T16:00:00",
        "equipment_type": "Dry Van",
        "loadboard_rate": 1650.00,
        "notes": "Liftgate required at delivery.",
        "weight": 28000.0,
        "commodity_type": "Electronics",
        "num_of_pieces": 15,
        "miles": 808.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-007",
        "origin": "Houston, TX",
        "destination": "Chicago, IL",
        "pickup_datetime": "2026-04-17T11:00:00",
        "delivery_datetime": "2026-04-19T07:00:00",
        "equipment_type": "Flatbed",
        "loadboard_rate": 2900.00,
        "notes": "Oversized load. Escort required through IL.",
        "weight": 47000.0,
        "commodity_type": "Steel Beams",
        "num_of_pieces": 4,
        "miles": 1092.0,
        "dimensions": "53x102",
        "status": "available",
    },
    {
        "load_id": "LD-008",
        "origin": "Charlotte, NC",
        "destination": "Boston, MA",
        "pickup_datetime": "2026-04-18T07:00:00",
        "delivery_datetime": "2026-04-19T14:00:00",
        "equipment_type": "Dry Van",
        "loadboard_rate": 2100.00,
        "notes": "Medical grade. Clean van required. No hazmat.",
        "weight": 18000.0,
        "commodity_type": "Medical Supplies",
        "num_of_pieces": 40,
        "miles": 868.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-009",
        "origin": "Kansas City, MO",
        "destination": "Memphis, TN",
        "pickup_datetime": "2026-04-17T13:00:00",
        "delivery_datetime": "2026-04-18T10:00:00",
        "equipment_type": "Reefer",
        "loadboard_rate": 1400.00,
        "notes": "Temp set to 36°F. Single stop.",
        "weight": 34000.0,
        "commodity_type": "Dairy Products",
        "num_of_pieces": 22,
        "miles": 450.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-010",
        "origin": "Portland, OR",
        "destination": "Salt Lake City, UT",
        "pickup_datetime": "2026-04-19T08:00:00",
        "delivery_datetime": "2026-04-20T14:00:00",
        "equipment_type": "Flatbed",
        "loadboard_rate": 1850.00,
        "notes": "Lumber load. Chains and binders provided.",
        "weight": 45000.0,
        "commodity_type": "Lumber",
        "num_of_pieces": 1,
        "miles": 773.0,
        "dimensions": "53x102",
        "status": "available",
    },
    {
        "load_id": "LD-011",
        "origin": "Minneapolis, MN",
        "destination": "Cleveland, OH",
        "pickup_datetime": "2026-04-18T06:00:00",
        "delivery_datetime": "2026-04-19T12:00:00",
        "equipment_type": "Dry Van",
        "loadboard_rate": 2250.00,
        "notes": "Food grade. Drop and hook available.",
        "weight": 39000.0,
        "commodity_type": "Packaged Foods",
        "num_of_pieces": 30,
        "miles": 762.0,
        "dimensions": "53x102",
        "status": "available",
    },
    {
        "load_id": "LD-012",
        "origin": "Philadelphia, PA",
        "destination": "Jacksonville, FL",
        "pickup_datetime": "2026-04-17T09:00:00",
        "delivery_datetime": "2026-04-19T11:00:00",
        "equipment_type": "Dry Van",
        "loadboard_rate": 2750.00,
        "notes": "Blanket wrap required. High-value freight.",
        "weight": 22000.0,
        "commodity_type": "Furniture",
        "num_of_pieces": 18,
        "miles": 1060.0,
        "dimensions": "53x102",
        "status": "available",
    },
    {
        "load_id": "LD-013",
        "origin": "Las Vegas, NV",
        "destination": "Albuquerque, NM",
        "pickup_datetime": "2026-04-19T10:00:00",
        "delivery_datetime": "2026-04-20T16:00:00",
        "equipment_type": "Reefer",
        "loadboard_rate": 1300.00,
        "notes": "Temp set to 32°F. Ice cream load.",
        "weight": 30000.0,
        "commodity_type": "Frozen Desserts",
        "num_of_pieces": 20,
        "miles": 484.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-014",
        "origin": "St. Louis, MO",
        "destination": "Pittsburgh, PA",
        "pickup_datetime": "2026-04-18T10:00:00",
        "delivery_datetime": "2026-04-19T18:00:00",
        "equipment_type": "Flatbed",
        "loadboard_rate": 2050.00,
        "notes": "Heavy equipment. Coil securement needed.",
        "weight": 46500.0,
        "commodity_type": "Steel Coils",
        "num_of_pieces": 3,
        "miles": 610.0,
        "dimensions": "48x102",
        "status": "available",
    },
    {
        "load_id": "LD-015",
        "origin": "San Antonio, TX",
        "destination": "Oklahoma City, OK",
        "pickup_datetime": "2026-04-17T14:00:00",
        "delivery_datetime": "2026-04-18T09:00:00",
        "equipment_type": "Dry Van",
        "loadboard_rate": 1250.00,
        "notes": "Partial load. 28ft trailer acceptable.",
        "weight": 14000.0,
        "commodity_type": "Auto Parts",
        "num_of_pieces": 12,
        "miles": 398.0,
        "dimensions": "28x102",
        "status": "available",
    },
]


def seed():
    init_db()
    db = SessionLocal()
    try:
        existing = db.query(Load).count()
        if existing > 0:
            print(f"Database already has {existing} loads. Skipping seed.")
            return
        for data in LOADS:
            db.add(Load(**data))
        db.commit()
        print(f"Seeded {len(LOADS)} loads successfully.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
